repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-yaml
      - id: check-case-conflict
      - id: check-xml
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [yaml]
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --verbose
        language: system
        types_or: [python, pyi]

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix --config=pyproject.toml
        language: system
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy --config-file=pyproject.toml ./src/plexosdb
        language: system
        types: [python]
        pass_filenames: false
